[package]
name = "package_json_schema"
version = "0.0.0"
authors = ["Ifiok Jr. <ifiokotung@gmail.com>"]
documentation = "https://docs.rs/package_json_schema"
edition = "2021"
include = ["src/**/*.rs", "Cargo.toml", "readme.md"]
repository = "https://github.com/skribbledev/skribble/tree/main/crates/package_json_schema"
description = "Parse widely used JSON file formats to their equivalent rust structs."

[lib]
crate-type = ["lib"]

[dependencies]
cfg-if = "1.0.0"
indexmap = { version = "1", features = ["serde-1"] }
lazy_static = "1"
regex = "1"
semver = "1"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order", "std"] }
thiserror = "1"
typed-builder = "0.10"
validator = { version = "0.16", features = ["derive"], optional = true }

[dev-dependencies]
insta = "1.17.1"

[features]
validate = ["validator"]
